version: "3.9"

services:
  mobius_wp:
    container_name: mobius_wp
    image: wordpress:6.2.2
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ../uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

    ports:
      - "8014:80"
    restart: always
    environment:
      VIRTUAL_HOST: mobius.tmy.io
      WORDPRESS_DB_HOST: globalmysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: mobius
    networks:
      - mysqlnet

networks:
  mysqlnet:
    external:
      name: mysqlnet